name: Terraform plan and Apply
on:
  workflow_dispatch:
  push:
    branches:
      - main
      #- test - This is to shows that multiple branches can be targeted for a specific event trigger.
      #- dev
      #- sandbox

  pull_request:
    branches:
      - main
 
permissions:
  contents: write
  pull-requests: read
  issues: write

concurrency: firstworkflow #This will ensure only a single workflow runs at a time

jobs:
  kics:
    name: Run KICS Code Analysis
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
         ref: ${{github.event.pull_request.head.ref}}

      - name: Run KICS Scan
        uses: checkmarx/kics-github-action@v2.0.0
        with: 
          path: ${{inputs.WORKING_DIRECTORY}}
          token: ${{ secrets.GITHUB_TOKEN }}
          output_path: myResults/
          ignore_on_exit: results
          enable_comments: ${{ inputs.ENABLE_COMMENTS }}


      - name: Display KICS results
        run:
          cat myResults/results.json

  run_plan_in_dev_environment:
    name: terraform init, validate , plan
    uses: ./.github/workflows/reusable_plan_actions.yml #means the path your workflow is located
    with:
      ENVIRONMENT_NAME: 'dev'
      TERRAFORM_VERSION: '1.7.4'
      TERRAGRUNT_VERSION:  '0.58.0'
      TERRAFORM_WORKING_DIR: './applied/dev'
      AWS_REGION: 'us-east-1'
    secrets: inherit

  run_apply_in_dev_environment:
    name: terraform init, apply
    needs: [run_plan_dev_environment]
    uses: ./.github/workflows/reusable_apply_actions.yml
    with:
      ENVIRONMENT_NAME: 'dev'
      TERRAFORM_VERSION: '1.7.4'
      TERRAGRUNT_VERSION:  '0.58.0'
      TERRAFORM_WORKING_DIR: './applied/dev'
      AWS_REGION: 'us-east-1'
    secrets: inherit

  run_plan_in_prod_environment:
    name: terraform init, validate , plan
    needs: [run_apply_dev_environment]
    uses: ./.github/workflows/reusable_plan_actions.yml # means the path your workflow is located
    with:
      ENVIRONMENT_NAME: 'prod'
      TERRAFORM_VERSION: '1.1.1'
      TERRAGRUNT_VERSION:  '0.56.0'
      TERRAFORM_WORKING_DIR: './applied/prod'
      AWS_REGION: 'us-east-1'
    secrets: inherit

  run_apply_in_prod_environment:
    name: terraform init, apply
    needs: [run_plan_prod_environment]
    uses: ./.github/workflows/reusable_plan_actions.yml
    with:
      ENVIRONMENT_NAME: 'prod'
      TERRAFORM_VERSION: '1.7.2'
      TERRAGRUNT_VERSION:  '0.58.0'
      TERRAFORM_WORKING_DIR: './applied/prod'
      AWS_REGION: 'us-east-1'
    secrets: inherit